include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    cascade_invocations: ignore
    invalid_annotation_target: ignore
    prefer_asserts_with_message: ignore
  exclude:
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - lib/l10n/**
    # Want to include generated files into your analysis? comment the following:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

linter:
  rules:
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    cascade_invocations: false
    public_member_api_docs: false
    prefer_single_quotes: false
    always_use_package_imports: false

    prefer_double_quotes: true
    flutter_style_todos: true
    prefer_relative_imports: true

formatter:
  page_width: 80
  trailing_commas: preserve

plugins:
  riverpod_lint: 3.1.3
