name: braintree_tests
description: "a braintree sandbox project"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1
  flutter: ^3.41.4

dependencies:
  flutter:
    sdk: flutter
  very_good_analysis: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
