# copy this file to mise.local.toml and fill in your local configuration
# the configuration should be available into https://sandbox.braintreegateway.com/
# (yes we're just using the sandbox environment for now - but it'll be pretty similar in production)
[env]
BRAINTREE_MERCHANT_ID = "..."
BRAINTREE_PUBLIC_KEY = "..."
BRAINTREE_PRIVATE_KEY = "..."
STRIPE_SECRET_KEY = "..."
STRIPE_WEBHOOK_SECRET = "..."
